Replace windows convert case functions
cse-sim/cse pull request #257
Opened 2022-05-06 14:58 UTC by galanCA

## Description

Replace the content in this section with:
- The motivation and context for this change (if it is not immediately clear from the title)
- If it fixes an open issue, specify the issue number (e.g., "fixes #XXXX")
- A summary of the behavior expected from this change
- A description of tests performed

## Author Progress Checklist:

- [ ] Open draft pull request
    - [ ] Make title clearly understandable in a standalone change log context
    - [ ] Assign yourself the issue
    - [ ] Add at least one label (enhancement, bug, or maintenance)
    - [ ] Link the issue(s) addressed by this PR (under "Development" in the sidebar menu) 
- [ ] Make code changes (if you haven't already)
- [ ] Self-review of code
    - [ ] My code follows the style guidelines of this project
    - [ ] I have added comments to my code, particularly in hard-to-understand areas
    - [ ] I have only committed the necessary changes for this fix or feature
    - [ ] I have made corresponding changes to the documentation
    - [ ] My changes generate no new warnings
    - [ ] I have ensured that my fix is effective or that my feature works as intended by:
        - [ ] exercising the code changes in the test framework, and/or
        - [ ] manually verifying the changes (as explained in the the pull request description above)
    - [ ] My changes pass all local tests
    - [ ] My changes successfully passes CI checks
    - [ ] Add any unit test for proof and documentation.
    - [ ] Merge in main branch and address resulting conflicts and/or test failures.
- [ ] Move pull request out of draft mode and assign reviewers
- [ ] Iterate with reviewers until all changes are approved
    - [ ] Make changes in response to reviewer comments
    - [ ] Merge in main branch and address resulting conflicts and/or test failures.
    - [ ] Re-request review in GitHub

## Reviewer Checklist:

 - [ ] Read the pull request description
 - [ ] Perform a code review on GitHub
 - [ ] Confirm all CI checks pass and there are no build warnings
 - [ ] Pull, build, and run automated tests locally
 - [ ] Perform manual tests of the fix or feature locally
 - [ ] Add any review comments, if applicable
 - [ ] Submit review in GitHub as either
     - [ ] Request changes, or
     - [ ] Approve
 - [ ] Iterate with author until all changes are approved

2022-05-06 15:42 UTC, chipbarnaby requested changes
I don't think this is the right approach, especially compareCaseStr().  We do not want to pay the price of constructing std::strings just to be able to compare them.  That often involves memory allocation.

I believe there are valid standard functions for all the null terminated string operations we want to do.  Actually, is it known that the current functions are not available via libraries on other platforms?  I believe we are using standard C functions that are generally widely supported.  In other words, why is this necessary at all (or so broadly necessary).

At some point we may convert to using std::string, at which point std::string operations can be used without unnecessary conversion.

2022-05-12 17:03 UTC, galanCA commented
I will implement a similar system as PR #256.

2022-05-12 17:03 UTC, galanCA commented
I will implement a similar system as PR #256.

2022-07-27 15:13 UTC, tanaya-bigladder requested changes

2022-07-27 15:13 UTC, tanaya-bigladder commented on test/unit/strpak.unit.cpp
> +	char randomCaseString[] = "Hello There ARE many case HERE!";
Perhaps the random case string could also put an upper-case letter in the middle of a word.

2022-07-27 15:13 UTC, tanaya-bigladder commented on test/unit/strpak.unit.cpp
> +	char randomCaseString[] = "Hello There ARE many case HERE!";
Also, "there are many case**s**" here. :)

2022-07-27 15:13 UTC, tanaya-bigladder commented on test/unit/strpak.unit.cpp
> +	char numberString[] = "There are 12311 numbers (#).";
Should we also test number/letter mixed words, as you sometimes see in variable names, e.g. "ASHRAE205"

2022-08-08 20:41 UTC, tanaya-bigladder submitted a review, later dismissed

2022-08-08 20:41 UTC, tanaya-bigladder commented on test/unit/strpak.unit.cpp
> +	strcpy(number_string, "Testing numbers: ASHRAE205, 1252345 (#).");
I would create a new char array here; the reason is that if someone wanted to update this function later on, they could mistakenly strcpy a longer string into an already allocated char array and have a memory leak.

2022-11-01 20:21 UTC, chipbarnaby requested changes
There could be trouble here due to signed characters.  tolower / toupper take integers.  That means a char > 127 will become a negative value.  The standard work-around is the following or words to that effect.

char* _strlwr(char* s)
{
    char* tmp = s;

    for (;*tmp;++tmp) {
        *tmp = tolower((unsigned char) *tmp);
    }

    return s;
}


This character stuff has always been tricky, but I think defining _strupr and _strlwr is a good enough solution pending conversion to std::string.

I would flag these functions as ?MULTIPLATFORM? -- this will work but certainly not elegant.

2022-11-01 20:46 UTC, chipbarnaby approved these changes

2022-11-03 14:49 UTC, nealkruis approved these changes

2022-11-03 14:49 UTC, nealkruis commented
@tanaya-bigladder merging is currently blocked because of your "request changes". Can you re-review?

2022-11-03 20:44 UTC, merged

2022-11-04 14:37 UTC, tanaya-bigladder reviewed
Approved; sorry it got out of sync.