Delete cdecl and replace function.
cse-sim/cse pull request #293
Opened 2022-05-27 16:29 UTC by galanCA

## Description

Replace the content in this section with:
- The motivation and context for this change (if it is not immediately clear from the title)
- If it fixes an open issue, specify the issue number (e.g., "fixes #XXXX")
- A summary of the behavior expected from this change
- A description of tests performed

## Author Progress Checklist:

- [ ] Open draft pull request
    - [ ] Make title clearly understandable in a standalone change log context
    - [ ] Assign yourself the issue
    - [ ] Add at least one label (enhancement, bug, or maintenance)
    - [ ] Link the issue(s) addressed by this PR (under "Development" in the sidebar menu) 
- [ ] Make code changes (if you haven't already)
- [ ] Self-review of code
    - [ ] My code follows the style guidelines of this project
    - [ ] I have added comments to my code, particularly in hard-to-understand areas
    - [ ] I have only committed the necessary changes for this fix or feature
    - [ ] I have made corresponding changes to the documentation
    - [ ] My changes generate no new warnings
    - [ ] I have ensured that my fix is effective or that my feature works as intended by:
        - [ ] exercising the code changes in the test framework, and/or
        - [ ] manually verifying the changes (as explained in the the pull request description above)
    - [ ] My changes pass all local tests
    - [ ] My changes successfully passes CI checks
    - [ ] Add any unit test for proof and documentation.
    - [ ] Merge in main branch and address resulting conflicts and/or test failures.
- [ ] Move pull request out of draft mode and assign reviewers
- [ ] Iterate with reviewers until all changes are approved
    - [ ] Make changes in response to reviewer comments
    - [ ] Merge in main branch and address resulting conflicts and/or test failures.
    - [ ] Re-request review in GitHub

## Reviewer Checklist:

 - [ ] Read the pull request description
 - [ ] Perform a code review on GitHub
 - [ ] Confirm all CI checks pass and there are no build warnings
 - [ ] Pull, build, and run automated tests locally
 - [ ] Perform manual tests of the fix or feature locally
 - [ ] Add any review comments, if applicable
 - [ ] Submit review in GitHub as either
     - [ ] Request changes, or
     - [ ] Approve
 - [ ] Iterate with author until all changes are approved

2022-11-03 16:29 UTC, nealkruis commented
@galanCA is this ready for review?

2022-11-11 14:24 UTC, tanaya-bigladder requested changes

2022-11-11 14:24 UTC, tanaya-bigladder commented on src/ashwat.cpp
> +#include <climits>
I didn't spot any place where this is being used? 
By the way, you're "adding climits header," not "adding climits library." :)

2023-08-10 21:47 UTC, spahrenk commented
Changed to vsnprintf and merged `main` into `ashwat-update`.

2024-05-27 21:06 UTC, nealkruis commented
Superseded by other PRs.

2024-05-27 21:06 UTC, closed without merging