32 bit TI (eliminate 32727 record limit)
cse-sim/cse pull request #503
Opened 2024-09-03 20:39 UTC by chipbarnaby

## Description

Change TI from 16 bit (int16_t) to 32 bit (int32_t).  This allows CSE to have more than 32767 records in a given RAT.

No results changes.  No documentation changes.

Note: modified code does not detect / handle other memory limits.  See issue 502.

2024-09-03 21:03 UTC, nealkruis requested changes
Looks fine. Just need to clean up temporary code.

2024-09-03 21:03 UTC, nealkruis commented on src/ancrec.h
> +#endif
Keep or remove?

2024-09-03 21:03 UTC, nealkruis commented on src/ancrec.h
> +    // void desRecs( TI mn=0, TI n=32767); 			// ~ all records or range (as b4 freeing block)
Keep or remove?

2024-09-03 21:07 UTC, chipbarnaby commented on src/ancrec.h
> +    // void desRecs( TI mn=0, TI n=32767); 			// ~ all records or range (as b4 freeing block)
Remove

2024-09-03 21:07 UTC, chipbarnaby commented on src/ancrec.h
> +#endif
Remove

2024-09-04 16:58 UTC, nealkruis approved these changes

2024-09-04 16:58 UTC, merged